### PR TITLE
Hello World in LOGO

### PR DESCRIPTION
**Pull request by Sanyam2000-dot**
#26 Created hello world program in LOGO

### CODE REVIEW

**Review by NishkarshRaj — COMMENTED** [review]
Hey @Sanyam2000-dot 
Thanks for raising this PR.

I have not heard about the LOGO programming. Can you please link its description so that I am sure your syntax is correct and then merge the PR.

I found this but this does not seem a match https://www.tutorialspoint.com/logo/index.htm

**Comment by Sanyam2000-dot** [comment]
Yaa sure http://www.logointerpreter.com/turtle-editor.php

**Review by NishkarshRaj — APPROVED** [review]

**Comment by Sanyam2000-dot** [comment]
Sir was it Hacktoberfest accepted?

**Comment by NishkarshRaj** [comment]
> 
> 
> Sir was it Hacktoberfest accepted?

Yes, the repository has a global Hacktoberfest tag.

**Comment by Sanyam2000-dot** [comment]
Not showing in the hacktoberfest dashboard!

**Comment by Sanyam2000-dot** [comment]
Moreover can you recommend my more repositories?

**Comment by NishkarshRaj** [comment]
I have added the label as well. Give it time, it will be accepted.

Cheap plug for more repositories : https://youtu.be/9fIN-871NPM?t=6317

**Comment by Sanyam2000-dot** [comment]
Thankyou sir!

**Pull request merged**
